apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- role.yaml
- role_binding.yaml
- service_account.yaml
- deployment.yaml

labels:
- includeSelectors: true
  pairs:
    app: activator
